export const schema = gql`
	"""
	Representation of ESNCard.
	"""
	type ESNCard {
		"Description for cardnumber."
		cardnumber: String!

		"Description for expiry."
		expiry: DateTime!

		"Description for section."
		section: String!

		"Description for person."
		person: Person!

		"Description for personId."
		personId: Int!
	}

	"""
	About queries
	"""
	type Query {
		"Fetch ESNCards."
		ESNCards: [ESNCard!]! @requireAuth

		"Fetch a ESNCard by id."
		ESNCard(cardnumber: String!): ESNCard @requireAuth
	}

	"""
	Autogenerated input type of InputESNCard.
	"""
	input CreateESNCardInput {
		"Description for cardnumber."
		cardnumber: String!

		"Description for expiry."
		expiry: DateTime!

		"Description for section."
		section: String!

		"Description for personId."
		personId: Int!
	}

	"""
	Autogenerated input type of UpdateESNCard.
	"""
	input UpdateESNCardInput {
		"Description for cardnumber."
		cardnumber: String!

		"Description for expiry."
		expiry: DateTime

		"Description for section."
		section: String

		"Description for personId."
		personId: Int
	}

	"""
	About mutations
	"""
	type Mutation {
		"Creates a new ESNCard."
		createESNCard(input: CreateESNCardInput!): ESNCard! @requireAuth

		"Updates an existing ESNCard."
		updateESNCard(cardnumber: String!, input: UpdateESNCardInput!): ESNCard! @requireAuth

		"Deletes an existing ESNCard."
		deleteESNCard(cardnumber: String!): ESNCard! @requireAuth
	}
`;
