export const schema = gql`
	"""
	Representation of MemberCard.
	"""
	type MemberCard {
		"Card number, 6 digits & 4 letters (000000AAAA)."
		cardnumber: String!

		"ESNCard'sexpiry date"
		expiry: DateTime!

		"GalaxyID of the section that sold this card"
		section: String!

		"Owner details"
		person: Person!

		"Owner's personId"
		personId: Int!
	}

	"""
	About queries
	"""
	type Query {
		"Fetch all ESNCards."
		memberCards: [MemberCard!]! @requireAuth

		"Fetch an ESNCard by its cardnumber."
		memberCard(cardnumber: String!): MemberCard @requireAuth
	}

	"""
	Autogenerated input type of InputMemberCard.
	"""
	input CreateMemberCardInput {
		"Card ID"
		cardnumber: String!

		"Owner's personId."
		personId: Int!
	}

	"""
	About mutations
	"""
	type Mutation {
		"Creates a new MemberCard."
		createMemberCard(input: CreateMemberCardInput!): MemberCard! @requireAuth

		"Deletes an existing MemberCard."
		deleteMemberCard(cardnumber: String!): MemberCard! @requireAuth
	}
`;
