export const schema = gql`
	"""
	Representation of Registration.
	"""
	type Registration {
		"Description for id."
		id: Int!

		"Description for person."
		person: Person!

		"Description for personId."
		personId: Int!

		"Description for payments."
		payments: [Payment]!
	}

	"""
	About queries
	"""
	type Query {
		"Fetch Registrations."
		registrations: [Registration!]! @requireAuth

		"Fetch a Registration by id."
		registration(id: Int!): Registration @requireAuth
	}

	"""
	Autogenerated input type of InputRegistration.
	"""
	input CreateRegistrationInput {
		"Description for personId."
		personId: Int!
	}

	"""
	Autogenerated input type of UpdateRegistration.
	"""
	input UpdateRegistrationInput {
		"Description for personId."
		personId: Int
	}

	"""
	About mutations
	"""
	type Mutation {
		"Creates a new Registration."
		createRegistration(input: CreateRegistrationInput!): Registration! @requireAuth

		"Updates an existing Registration."
		updateRegistration(id: Int!, input: UpdateRegistrationInput!): Registration! @requireAuth

		"Deletes an existing Registration."
		deleteRegistration(id: Int!): Registration! @requireAuth
	}
`;
